users_schema = """
EMAIL_ADDRESS VARCHAR PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
PREFERRED_NAME VARCHAR,
PASSWORD VARCHAR NOT NULL,
PHYSICAL_ID_NUM VARCHAR,
DOB DATE NOT NULL,
ROLE VARCHAR NOT NULL,
PHOTO VARCHAR NOT NULL,
IS_STAFF BOOLEAN NOT NULL,
IS_SUPERUSER BOOLEAN NOT NULL
"""

events_schema = """
EVENT_ID INTEGER PRIMARY KEY,
EVENT_NAME VARCHAR NOT NULL,
MEETING_LINK VARCHAR NOT NULL,
SUPER_LINK VARCHAR NOT NULL,
YEAR INTEGER,
SECTION VARCHAR
"""

event_roster_participant_schema = """
PARTICIPANT_ID INTEGER PRIMARY KEY,
ROSTER_ID INTEGER,
EMAIL_ADDRESS VARCHAR,
CONSTRAINT fk_roster FOREIGN KEY(roster_id) REFERENCES event_roster(roster_id)
"""

event_roster_schema = """
ROSTER_ID INTEGER PRIMARY KEY,
ROSTER_NAME VARCHAR NOT NULL
"""

event_enrollment_schema = """
ENROLLMENT_ID INTEGER PRIMARY KEY,
EVENT_ID INTEGER NOT NULL,
ROSTER_ID INTEGER NOT NULL,
CONSTRAINT fk_roster FOREIGN KEY(roster_id) REFERENCES event_roster(roster_id),
CONSTRAINT fk_event FOREIGN KEY(event_id) REFERENCES events(event_id) ON DELETE CASCADE
"""

event_schedule_schema = """
SCHEDULE_ID INTEGER PRIMARY KEY,
EVENT_ID INTEGER NOT NULL,
WEEKDAY INTEGER,
START_TIME TIME,
END_TIME TIME,
CONSTRAINT fk_event FOREIGN KEY(event_id) REFERENCES events(event_id) ON DELETE CASCADE
"""

assignments_schema = """
ASSIGNMENT_ID VARCHAR PRIMARY KEY,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR NOT NULL,
ASSIGNED_DATE DATE NOT NULL,
DUE_DATE DATE NOT NULL,
EVENT_ID INTEGER NOT NULL,
CONSTRAINT fk_event FOREIGN KEY(event_id) REFERENCES events(event_id) ON DELETE CASCADE
"""