users_schema = """
EMAIL_ADDRESS VARCHAR PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
PREFERRED_NAME VARCHAR,
PASSWORD VARCHAR NOT NULL,
PHYSICAL_ID_NUM VARCHAR,
DOB DATE NOT NULL,
ROLE VARCHAR NOT NULL,
PHOTO VARCHAR NOT NULL,
IS_STAFF BOOLEAN NOT NULL,
IS_SUPERUSER BOOLEAN NOT NULL
"""

classes_schema = """
CLASS_ID INTEGER PRIMARY KEY,
CLASS_NAME VARCHAR NOT NULL,
MEETING_LINK VARCHAR NOT NULL,
SUPER_LINK VARCHAR NOT NULL,
YEAR INTEGER,
SECTION VARCHAR
"""

class_enrollment_schema = """
ENROLLMENT_ID INTEGER PRIMARY KEY,
CLASS_ID INTEGER NOT NULL,
TEACHER_EMAIL VARCHAR,
STUDENT_EMAIL VARCHAR
"""

class_schedule_schema = """
SCHEDULE_ID INTEGER PRIMARY KEY,
CLASS_ID INTEGER NOT NULL,
WEEKDAY INTEGER,
START_TIME TIME,
END_TIME TIME
"""

assignments_schema = """
ASSIGNMENT_ID VARCHAR PRIMARY KEY,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR NOT NULL,
ASSIGNED_DATE DATE NOT NULL,
DUE_DATE DATE NOT NULL,
CLASS_ID INTEGER NOT NULL
"""